---
title: "R SCRAPING"
output: html_document
---


1、将标签做聚类分析
2、将标签做主成分分析
3、将标签做因子分析
4、回归分析预测评分
5、游戏名相似度研究

```{r}
library(rvest)
library(tidyverse)
library(lubridate)
library(caret)
library(stringdist)
library(cluster)
library(microbenchmark)
```

#单页爬取测试
```{r}
game <- read_html("https://dl.3dmgame.com/")

game %>% html_nodes(".bt a") %>% html_text(trim = TRUE) -> name_data  #游戏名,可输入节点名或属性名
game %>% html_nodes("ul li ol li i") %>% html_text(trim = TRUE) -> game_content #内容列表
game_content  #每6条信息循环一次
game_content[seq(1, length(game_content), 6)] -> type_data                          #类型
game_content[seq(2, length(game_content), 6)] %>% as.numeric() -> hot_data          #热度
game_content[seq(3, length(game_content), 6)] -> lang_data                          #语言 
game_content[seq(4, length(game_content), 6)] %>% as.numeric() -> score_data        #评分
game_content[seq(5, length(game_content), 6)]                                       #发布时间
game_content[seq(6, length(game_content), 6)] -> platform_data                      #平台
game_df_test <- tibble(name = name_data, 
                       type = type_data,
                       hot = hot_data,
                       lang = lang_data,
                       score = score_data,
                       date = date_data,
                       platform = platform_data)
game %>% html_nodes("ul li .a_click") %>% html_text(trim = TRUE) %>% str_extract("\\(.+\\)") %>% str_replace_all("[\\(\\)]", "")  #游戏大小
game %>% html_nodes("li .li2") %>% html_text(trim = TRUE) %>% str_replace_all("[标签：|\n]", "") %>% str_trim(side = "both") %>% str_replace_all("\\s+", ",")  #标签
game %>% html_nodes("div .listwrap a img") %>% html_attr("src") #图片链接
game %>% html_nodes("div .bt a") %>% html_attr("href")          #内容链接

#用selector Gadget定位
game %>% html_nodes(".bt a") %>% html_text(trim = TRUE)                             #游戏名
game %>% html_nodes(".li1 i") %>% html_text(trim = TRUE)                            #热度
game %>% html_nodes(".text li:nth-child(1) i") %>% html_text(trim = TRUE)           #类型
game %>% html_nodes(".li1+ li i") %>% html_text(trim = TRUE)                        #语言
game %>% html_nodes(".text li:nth-child(4) i") %>% html_text(trim = TRUE)           #评分
game %>% html_nodes(".text li:nth-child(5) i") %>% html_text(trim = TRUE)           #发布时间
game %>% html_nodes(".text li:nth-child(6) i") %>% html_text(trim = TRUE)           #平台
game %>% html_nodes(".bt a") %>% html_attr("href")                                  #内容链接
game %>% html_nodes(".item img") %>% html_attr("src")                               #图片链接
game %>% 
  html_nodes(".a_click") %>% 
  html_text(trim = TRUE) %>% 
  str_extract("\\(.+\\)") %>%     
  str_replace_all("[\\(\\)]", "")                                                   #游戏大小
game %>% 
  html_nodes(".li2") %>% 
  html_text(trim = TRUE) %>% 
  str_replace_all("[标签：|\n]", "") %>% 
  str_trim(side = "both") %>% 
  str_replace_all("\\s+", ",")                                                      #标签
```

#全网爬取
```{r}
url_1 <- "https://dl.3dmgame.com/all_all_"
url_2 <- "_time/"
game_df <- tibble()    #生成初始数据框

for (i in 1:1843){
  
  url <- paste0(url_1, i, url_2)
  game <- read_html(url)
  
  game %>% html_nodes(".bt a") %>% html_text(trim = TRUE) -> name_data                                   #游戏名
  game %>% html_nodes(".text li:nth-child(1) i") %>% html_text(trim = TRUE) -> type_data                 #类型
  game %>% html_nodes(".li1 i") %>% html_text(trim = TRUE) %>% as.numeric() -> hot_data                  #热度
  game %>% html_nodes(".li1+ li i") %>% html_text(trim = TRUE) -> lang_data                              #语言 
  game %>% html_nodes(".text li:nth-child(4) i") %>% html_text(trim = TRUE) -> score_data                #评分
  game %>% html_nodes(".text li:nth-child(5) i") %>% html_text(trim = TRUE) %>% as.Date() -> date_data   #发布时间
  game %>% html_nodes(".text li:nth-child(6) i") %>% html_text(trim = TRUE) -> platform_data             #平台
  game %>% html_nodes("div .listwrap a img") %>% html_attr("src") -> img_link_data                       #图片链接
  game %>% html_nodes("div .bt a") %>% html_attr("href") -> content_link_data                            #内容链接
  game %>% 
    html_nodes(".a_click") %>% 
    html_text(trim = TRUE) %>% 
    str_extract("\\(.+\\)") %>%     
    str_replace_all("[\\(\\)]", "") -> size_data   #游戏大小
  game %>% 
    html_nodes(".li2") %>% 
    html_text(trim = TRUE) %>% 
    str_replace_all("[标签：|\n]", "") %>% 
    str_trim(side = "both") %>% 
    str_replace_all("\\s+", ",") -> label_data     #标签
  
  game_df_i <- tibble(name = name_data, 
                      type = type_data,
                      hot = hot_data,
                      lang = lang_data,
                      score = score_data,
                      date = date_data,
                      platform = platform_data,
                      size = size_data,
                      label = label_data,
                      img_link = img_link_data,
                      content_link = content_link_data)
  game_df <- bind_rows(game_df, game_df_i)
}
game_df
```

#数据清理
```{r}
#清理名称、空间
game_df %>% 
  mutate(name = str_extract(name, "《.+》")) %>%
  mutate(name = str_replace_all(name, "[《|》]", "")) %>% 
  mutate(id = row_number(), GB = str_detect(size, "GB"),
         size2 = as.numeric(str_replace_all(size, "[A-Za-z]", "")),
         size_mb = if_else(GB, size2 * 1024, size2)) %>% 
  select(-c(hot, GB, size, size2))-> game_df_c

#清理标签
game_df_c %>% 
  select(id, label) %>% 
  mutate(label = str_split(label, ",")) %>% 
  unnest() %>% 
  count(id, label) %>% 
  spread(key = label, value = n, fill = 0, drop = TRUE) %>% 
  select(-V1) -> game_label

#合并数据
game_df_c %>% inner_join(game_label, by = "id") %>% 
  select(id, everything(), -label, -platform) -> game_df_c  #调整ID列位置
game_df_c

#保留完整样本
game_df_c %>% 
  na.omit() %>% 
  filter(type != "" & lang != "") -> game_df_full
game_df_full
```

#描述分析
```{r, fig.height=5, fig.width=15}
#标签出现数量
game_df_full %>% 
  select(-c(name, type, lang, score, date, size_mb)) %>% 
  gather(key = label, value = n, c(DC:`足球`)) %>% #宽数据转长数据
  group_by(label) %>% 
  summarise(sum = sum(n)) %>% 
  arrange(desc(sum))

#类型与评分
game_df_full %>% count(type) %>% arrange(desc(n))
game_df_full %>% 
  group_by(type) %>% 
  summarise(mean_score = mean(score)) %>% 
  arrange(desc(mean_score)) %>% filter(type != "")

#语言与评分
game_df_full %>% count(lang) %>% arrange(desc(n))
game_df_full %>% 
  group_by(lang) %>% 
  summarise(mean_score = mean(score)) %>% 
  arrange(desc(mean_score))

#面积与评分
game_df_full %>% select(size_mb) %>% summary()
game_df_full %>% 
  ggplot(aes(size_mb, score)) +
  geom_point() +
  scale_x_log10()

#年份与评分
game_df_full %>% 
  mutate(year = year(date),
         time = 2020 - year) -> game_df_full
game_df_full %>% 
  group_by(time) %>% 
  summarise(mean_score = mean(score)) %>% 
  arrange(time) %>% 
  ggplot(aes(time, mean_score)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(1, 20, 1))
```

#标签主成分
```{r, fig.height=5, fig.width=15}
game_df_full %>% 
  select(DC:`足球`) %>% 
  prcomp() -> label_pca2
summary(label_pca2) #第一行标准差平方为解释了多少方差，第二行为解释的方差占方差总和的比例，第三行为累计解释的方差
label_pca2$sdev %>% head()
label_pca2$rotation %>% head()
label_pca2$x[1:10, 1:8] #各样本在不同主成分上的负载，用于回归，等同于princomp的score
plot(label_pca2, type = "lines", main = "Screeplot")
pca_df <- tibble(sdev = label_pca2$sdev, 
                 var = label_pca2$sdev ^ 2,
                 var_prop = var / sum(var),
                 var_prop_cum = cumsum(var_prop)
                 ) %>% mutate(n = row_number())
pca_df %>% 
  ggplot(aes(n, var_prop_cum)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 140, 5)) +
  scale_y_continuous(breaks = seq(0, 1, 0.1)) +
  theme(axis.text = element_text(size = 10),
        panel.grid.minor = element_blank()) + 
  labs(x = "主成分数", y = "累计解释方差") +
  ggtitle("Screeplot of Cumulative Variance")
```

#评分预测
```{r}
#将主成分结果加入
label_pca2$x %>% as.tibble() -> label_pca_tib
game_df_full %>% 
  select(score, type, lang, time, size_mb) %>% 
  bind_cols(label_pca_tib[1:38]) -> game_df_model    #保留38个主成分
game_df_model

#字符转化为因子
game_df_model %>% 
  mutate(type_fac = as.factor(type),
         lang_fac = as.factor(lang)) %>% 
  select(score, time, size_mb, type_fac, lang_fac, everything(),-type, -lang, ) -> game_df_model_fac
game_df_model_fac
sapply(game_df_model_fac, class)
```

#模型训练
```{r}
#基本回归
lm_model <- lm(score ~ ., data = game_df_model_fac)
summary(lm_model)
```

```{r}
#caret包:结果和lm基本一样
lm_model_train <- train(score ~ .,
                        data = game_df_model_fac,
                        method = "lm",
                        trControl = trainControl(method = "cv", number = 5)
                        )
lm_model_train
summary(lm_model_train)
```

```{r}
#R Clent优化回归
formula <- score ~ time + size_mb + type_fac + lang_fac + PC1 + PC2 +PC3 +PC4 + PC5 + PC6 + PC7 + PC8 +
  PC9 + PC10 + PC11 + PC12 + PC13 + PC14 + PC15 + PC16 + PC17 + PC18 + PC19 + PC20 + PC21 + PC22 + PC23 + 
  PC24 +PC25 + PC26 + PC27 + PC28 + PC29 + PC30 + PC31 + PC32 + PC33 + PC34 + PC35 + PC36 + PC37 + PC38
rx_lm_model <- rxLinMod(formula, data = game_df_model_fac)
summary(rx_lm_model)
```

```{r}
microbenchmark(lm(score ~ ., data = game_df_model_fac),
               rxLinMod(formula, data = game_df_model_fac),
               train(score ~ .,
                        data = game_df_model_fac,
                        method = "lm",
                        trControl = trainControl(method = "cv", number = 5)
                        ),
               unit = "ms")
```


```{r}
#计算样本两两之间的距离，包括类别变量及数值变量
game_dist <- game_df_model[, c("type", "lang", "size_mb", "time")]
game_dist$type <- as.factor(game_dist$type)
game_dist$lang <- as.factor(game_dist$lang)
game_dist_daisy <- daisy(game_dist, metric = "gower")
game_dist_daisy %>% head()
str(game_dist_daisy)
```




#相似度研究

1、expand.grid 和 combn 哪个快
2、优化为topn
```{r}
game_df %>% 
  select(name) %>% 
  mutate(name1 = str_replace_all(name, "[《|》|安装|版|免|英文|中文|简体|游戏库|硬盘|：|\\s]", ""),
         name2 = name1) %>% 
  select(-name) -> game_name
game_name
# game_name_com <- expand.grid(game_name$name1, game_name$name2, stringsAsFactors = FALSE)
game_name_com %>% as.tibble() %>% rename(name1 = Var1, name2 = Var2) -> game_name_com
game_name_com
game_name_com %>%
  mutate(lv_dist = stringdist(name1, name2, method = "lv")) %>% 
  group_by(name1) %>% 
  summarise(match_dist = lv_dist[which.min(lv_dist)],
            match_name = name2[which.min(lv_dist)]) -> game_name_match
game_name_match
```

```{r}
game_name %>% top_n(1000) -> game_name_1000
game_name_1000
game_name_com_1000 <- expand.grid(game_name_1000$name1, game_name_1000$name2, stringsAsFactors = FALSE)
game_name_com_1000 %>% as.tibble() %>% rename(name1 = Var1, name2 = Var2) -> game_name_com_1000
game_name_com_1000 %>%
  mutate(lv_dist = stringdist(name1, name2, method = "lv")) %>% 
  group_by(name1) %>% 
  summarise(match_dist = lv_dist[which.min(lv_dist)],
            match_name = name2[which.min(lv_dist)]) -> game_name_match_1000
game_name_match_1000
```

